In [2]:


#importing numpy libarary, It provides support for large, multi-dimensional arrays and matrices
import numpy as np
#importing numpy libarary, It provides support for data manipulation and analysis. 
import pandas as pd
# importing matplotlib.pyplot plotting library in Python that provides a MATLAB-like interface for creating visualizations. 
import matplotlib.pyplot as plt

In [3]:
#Reading the csv file using pandas function and saved in data variable
data = pd.read_csv("50_Startups.csv")

In [4]:
data = pd.get_dummies(data, drop_first=True)#1st column is dropped, CA is dropped

In [5]:
data.head()

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83              0   
1  162597.70       151377.59        443898.53  191792.06              0   
2  153441.51       101145.55        407934.54  191050.39              1   
3  144372.41       118671.85        383199.62  182901.99              0   
4  142107.34        91391.77        366168.42  166187.94              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [6]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
dependet =data[["Profit"]]

independet =data[["R&D Spend","Administration", "Marketing Spend", "State_Florida","State_New York"]]

In [8]:
#importing train_test_split from sklearn.model_selection which is used for splitting the data into train and test
from sklearn.model_selection import train_test_split

#splitting Xtrain,X_test, y_train and y_test usiing train_test_split function. Train and test split ratio is 70% and 30% respectively
X_train, X_test, y_train, y_test = train_test_split(independet, dependet, test_size=0.30, random_state=0)

In [9]:
X_train.size, X_test.size, y_train.size, y_test.size

(175, 75, 35, 15)

In [236]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #transfrom perform caluclation   (mu,sigma)
X_test = sc.fit_transform(X_test)

In [251]:
from sklearn.svm import SVR

regressor = SVR(kernel = "sigmoid", C=5000)
#regressor is fitting the X-train and y_train data
regressor.fit(X_train,y_train)

C:\Users\AB92922\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=5000, kernel='sigmoid')

In [252]:
regressor.n_support_

array([35])

In [253]:
regressor.intercept_

array([108860.72270707])

In [254]:
#machine learning regressor (regressor) to make predictions and saved in y_pred variable
y_pred = regressor.predict(X_test)
y_pred

array([ 98856.6048857 , 124791.30867071, 123411.96874194,  72466.66212939,
       158094.85212008, 120334.96224239,  74446.7144943 ,  88443.57972935,
       116524.97858507, 152829.52350788,  92840.0644314 ,  88247.49409904,
       100334.45153724,  95039.5388228 , 125129.88659985])

In [255]:
#importing r2_score libarary from sklearn.metrics for model evaulvation
from sklearn.metrics import r2_score

In [256]:
#checking r2 square value between y_test and y_pred
r2_score =r2_score(y_test,y_pred)
#printing r2 square value   #  standardising value
r2_score

0.8118623865588022

In [257]:
r2_score

0.8118623865588022

In [ ]:
#rbf, poly, 